#!/bin/bash

yum install epel-release -y
yum install nginx -y
yum install python34-devel gcc -y
curl -O https://bootstrap.pypa.io/get-pip.py
/usr/bin/python3.4 get-pip.py

#Gets Python ready to roll.
pip install virtualenv
mkdir -p /var/www && cd /var/www
virtualenv -p python3 p3venv


#Sets up virtual environment.
source p3venv/bin/activate
pip install uwsgi
pip install django

##### Echo statement ######
echo -e "upstream django {
	server unix:/run/uwsgi/apivndeveloper.sock;
}

# configuration of the server
server {
	listen		80;
	server_name 	api.vndeveloper.com;
	charset		utf-8;
	# max upload size
	client_max_body_size 75M;
	# Django media & static
	location /media  {
		alias /var/www/apivndeveloper/media;
	}
	location /static {
		alias /var/www/apivndeveloper/static;
	}
	# Finally, send all non-media requests to the Django server.
	location / {
		uwsgi_pass  django;
		include uwsgi_params;
		
		uwsgi_param Host $host;
		uwsgi_param X-Real-IP $remote_addr;
		uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
		uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
	}
}" > /etc/nginx/conf.d/apivndeveloper.conf
######### End of echo statement ###############

#Stopped at 2.1 (https://www.vndeveloper.com/django-behind-uwsgi-nginx-centos-7/)
