#!/bin/bash
if [ -e /var/lib/pgsql/data/pg_hba.conf ]; then exit 0; fi
#Installs python package manager, GNU compiler, and Postgres.
yum install python-pip python-devel gcc postgresql-server postgresql-devel postgresql-contrib -y

postgresql-setup initdb

systemctl start postgresql

#Refer to https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-centos-7 for use on sed in the future.
sed -i.bak 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf

systemctl start postgresql
systemctl enable postgresql

#su - postgres
#psql


echo -e "CREATE DATABASE myproject;
\n
CREATE USER myprojectuser WITH PASSWORD 'password';
\n
ALTER ROLE myprojectuser SET client_encoding TO 'utf8';
\n
ALTER ROLE myprojectuser SET default_transaction_isolation TO 'read committed';
\n
ALTER ROLE myprojectuser SET timezone TO 'UTC';
\n
ALTER USER postgres WITH PASSWORD 'P@ssw0rd1';
GRANT ALL PRIVILEGES ON DATABASE myproject TO myprojectuser;" > sqlfile.sql

sudo -i -u postgres psql -U postgres -f /sqlfile.sql

systemctl restart postgresql

systemctl start postgresql

yum install phpPgAdmin -y

sed -i 's/Require local/Require all granted/g' /etc/httpd/conf.d/phpPgAdmin.conf

sed -i 's/Allow from 127.0.0.1/Allow from all/g' /etc/httpd/conf.d/phpPgAdmin.conf

sed -i 's/$conf\['\''extra_login_security'\''\] = true;/$conf\['\''extra_login_security'\''\] = false;/g' /etc/phpPgAdmin/config.inc.php
#ip/phpPgAdmin Usr: postgres PW: postgres
setenforce 0

#vim /var/lib/pgsql/data/pg_hba.conf ----> Edit "peer" to md5 in "local   all             all                                     peer"
sed -i 's/local   all             all                                     peer/local   all             all                                     md5/g' /var/lib/pgsql/data/pg_hba.conf


systemctl start httpd
systemctl enable httpd

#\q
#exit

#Django begins here.
#pip install virtualenv

#mkdir /myproject
#cd /myproject

#virtualenv myprojectenv
#source myprojectenv/bin/activate

#pip install django psycopg2

#django-admin.py startproject myproject .

#Stopped at "Configure the Django Database Settings".
