#!/bin/bash

#Installs python package manager, GNU compiler, and Postgres.
yum install python-pip python-devel gcc postgresql-server postgresql-devel postgresql-contrib -y

postgresql-setup initdb

systemctl start postgresql

#Refer to https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-centos-7 for use on sed in the future.
#Experimental: sed -i.bak 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf

systemctl restart postgresql
systemctl enable postgresql

su - postgres
psql
CREATE DATABASE myproject;
CREATE USER myprojectuser WITH PASSWORD 'password';

ALTER ROLE myprojectuser SET client_encoding TO 'utf8';
ALTER ROLE myprojectuser SET default_transaction_isolation TO 'read committed';
ALTER ROLE myprojectuser SET timezone TO 'UTC';

GRANT ALL PRIVILEGES ON DATABASE myproject TO myprojectuser;

\q
exit

pip install virtualenv

mkdir /myproject
cd /myproject

virtualenv myprojectenv
source myprojectenv/bin/activate

pip install django psycopg2

django-admin.py startproject myproject .

#Stopped at "Configure the Django Database Settings".
