#!/bin/bash
if [ -e /django-server-auto.sh ]; then exit 0; fi

gcloud init
1
nti-310-200201


yum install wget -y
wget https://github.com/Tedtanium/nti-310-linux-enterprise-applications/raw/master/postgres-install
wget https://github.com/Tedtanium/nti-310-linux-enterprise-applications/raw/master/django-server-auto.sh


gcloud compute firewall-rules create httpenable --allow tcp:80
# ^ Still busted -- May need a different command to enable HTTP access.
gcloud compute instances create postgres-a --metadata-from-file postgres=/postgres-install --image-family=centos-7 --tags httpenable --zone us-east1-b

gcloud compute instances create django-a --metadata-from-file django=/django-server-auto.sh --image-family=centos-7 --tags httpenable --zone us-east1-b


#--image-project=centos-cloud

#postgres-install

#djangoip=$(gcloud compute instances list | grep postgres | awk '{print $4}')
# ^ No longer needed. This function is now handled from within the django script itself without Google API.
#django-server-auto.sh

#WIP.
